apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo
resources:
  - https://github.com/argoproj/argo-workflows/releases/download/v4.0.5/quick-start-minimal.yaml
  - namespace.yaml
  - ingress.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
