---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: additional-addons
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/mzeeshan1/addons.git
        revision: HEAD
        directories:
          - path: "additional-addons/*"
  template:
    metadata:
      name: "{{ "{{" }}.path.basename{{ "}}" }}"
    spec:
      project: addons
      source:
        repoURL: https://github.com/mzeeshan1/addons.git
        targetRevision: HEAD
        path: "{{ "{{" }}.path.path{{ "}}" }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ "{{" }}.path.basename{{ "}}" }}"
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true