---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
  creationTimestamp: null
  name: addons
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: addons project
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"
status: {}
