kube-prometheus-stack:
  grafana:
    ingress:
      enabled: true
      hosts:
        - grafna.heimbuero-test.de
      tls:
        - secretName: grafana-general-tls
          hosts:
            - grafana.heimbuero-test.de
