---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ECRAuthorizationToken
metadata:
  name: ecr-token
  namespace: argocd
spec:
  region: eu-central-1
---
{{- $op := "{{" }}
{{- $cl := "}}" }}
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ECRAuthorizationToken
metadata:
  name: ecr-token
  namespace: argocd
spec:
  region: eu-central-1
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ecr-credentials
  namespace: argocd
spec:
  refreshInterval: 6h
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ECRAuthorizationToken
          name: ecr-token
  target:
    name: ecr-credentials
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        .dockerconfigjson: |
          {{ $op }} printf "{\"auths\":{\"783149339345.dkr.ecr.eu-central-1.amazonaws.com\":{\"username\":%s,\"password\":%s}}}" (.username | b64dec | toJson) (.password | b64dec | toJson) {{ $cl }}