---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ECRAuthorizationToken
metadata:
  name: ecr-token
  namespace: argocd
spec:
  region: eu-central-1
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ecr-credentials
  namespace: argocd
spec:
  refreshInterval: 6h
  data:
    - secretKey: password
      sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ECRAuthorizationToken
          name: ecr-token
      remoteRef:
        key: password
    - secretKey: username
      sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ECRAuthorizationToken
          name: ecr-token
      remoteRef:
        key: username
  target:
    name: ecr-credentials
    template:
      type: kubernetes.io/dockerconfigjson
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "783149339345.dkr.ecr.eu-central-1.amazonaws.com": {
                "username": "{{ .username }}",
                "password": "{{ .password }}"
              }
            }
          }
