{{- $op := "{{" }}
{{- $cl := "}}" }}
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ECRAuthorizationToken
metadata:
  name: ecr-token
  namespace: argocd
spec:
  region: eu-central-1
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ecr-repository
  namespace: argocd
spec:
  refreshInterval: 6h
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ECRAuthorizationToken
          name: ecr-token
  target:
    name: ecr-repository
    template:
      engineVersion: v2
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        username: "AWS"
        type: "helm"
        url: "oci://783149339345.dkr.ecr.eu-central-1.amazonaws.com"
        enableOCI: "true"
        password: |
          {{ $op }} .password | toJson {{ $cl }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ecr-credentials
  namespace: argocd
spec:
  refreshInterval: 6h
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ECRAuthorizationToken
          name: ecr-token
  target:
    name: ecr-credentials
    template:
      engineVersion: v2
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        username: "AWS"
        type: "helm"
        url: "oci://783149339345.dkr.ecr.eu-central-1.amazonaws.com"
        enableOCI: "true"
        password: |
          {{ $op }} .password | toJson {{ $cl }}
