argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    extraArgs:
      - --insecure
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hostname: "argocd.emzien.click"
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
  repoServer:
    extraContainers:
      - name: helmfile-plugin
        command: [/var/run/argocd/argocd-cmp-server]
        image: travisghansen/argo-cd-helmfile:latest
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: helmfile.yaml
            name: argocd-cmp-cm
          - mountPath: /tmp
            name: cmp-tmp
    volumes:
      - name: cmp-tmp
        emptyDir: {}
      - name: argocd-cmp-cm
        configMap:
          name: argocd-cmp-cm
  configs:
    cmp:
      create: true
      plugins:
        helmfile:
          init:
            command: [sh, -c]
            args:
              - helmfile deps
          generate:
            command: [sh, -c]
            args:
              - helmfile template --include-crds
          discover:
            find:
              glob: "**/helmfile.yaml"
